# Generated by Django 5.2.6 on 2025-10-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='CÓDIGO')),
                ('correo_representante', models.EmailField(max_length=254, verbose_name='CORREO DEL REPRESENTANTE')),
                ('modalidad', models.CharField(choices=[('TRABAJO DE INVESTIGACIÓN', 'TRABAJO DE INVESTIGACIÓN'), ('MATERIALES EDUCATIVOS', 'MATERIALES EDUCATIVOS'), ('PROTOTIPO', 'PROTOTIPO'), ('REPORTE', 'REPORTE'), ('PROYECTOS DE VINCULACIÓN SOCIAL', 'PROYECTOS DE VINCULACIÓN SOCIAL')], max_length=50, verbose_name='MODALIDAD')),
                ('evidencia', models.FileField(upload_to='evidencias/', verbose_name='SUBE TU EVIDENCIA')),
            ],
        ),
    ]
